name: chroma
description: A color library for creating, converting and manipulating colors.
version: 0.0.1
author: Tomás Arias <hi@tomasarias.me>
homepage: https://tomasarias.me/chroma
repository: https://github.com/KNawm/chroma

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.1.0
  flutter_test:
    sdk: flutter