name: chroma
description: A color library.
version: 0.0.1
author: Tomás Arias <hi@tomasarias.me>
repository: https://github.com/KNawm/chroma

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.0.0
