name: chroma
version: 0.1.0-dev
description: A color library for creating, converting and manipulating colors.
homepage: https://github.com/KNawm/chroma
repository: https://github.com/KNawm/chroma

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.1.0
  flutter_test:
    sdk: flutter