import 'package:chroma/chroma.dart';

List fromNamed(String value) {
  if (_namedColors.containsKey(value)) {
    final red = _namedColors[value].red.toDouble();
    final green = _namedColors[value].green.toDouble();
    final blue = _namedColors[value].blue.toDouble();

    final out = List(2)
      ..[0] = _namedColors[value].value
      ..[1] = {
        'r': red,
        'g': green,
        'b': blue,
        'a': 1.0,
      };

    return out;
  }
}

final _namedColors = {
  'aliceblue': Chroma('F0F8FF'),
  'antiquewhite': Chroma('FAEBD7'),
  'aqua': Chroma('00FFFF'),
  'aquamarine': Chroma('7FFFD4'),
  'azure': Chroma('F0FFFF'),
  'beige': Chroma('F5F5DC'),
  'bisque': Chroma('FFE4C4'),
  'black': Chroma('000000'),
  'blanchedalmond': Chroma('FFEBCD'),
  'blue': Chroma('0000FF'),
  'blueviolet': Chroma('8A2BE2'),
  'brown': Chroma('A52A2A'),
  'burlywood': Chroma('DEB887'),
  'cadetblue': Chroma('5F9EA0'),
  'chartreuse': Chroma('7FFF00'),
  'chocolate': Chroma('D2691E'),
  'coral': Chroma('FF7F50'),
  'cornflowerblue': Chroma('6495ED'),
  'cornsilk': Chroma('FFF8DC'),
  'crimson': Chroma('DC143C'),
  'cyan': Chroma('00FFFF'),
  'darkblue': Chroma('00008B'),
  'darkcyan': Chroma('008B8B'),
  'darkgoldenrod': Chroma('B8860B'),
  'darkgray': Chroma('A9A9A9'),
  'darkgreen': Chroma('006400'),
  'darkgrey': Chroma('A9A9A9'),
  'darkkhaki': Chroma('BDB76B'),
  'darkmagenta': Chroma('8B008B'),
  'darkolivegreen': Chroma('556B2F'),
  'darkorange': Chroma('FF8C00'),
  'darkorchid': Chroma('9932CC'),
  'darkred': Chroma('8B0000'),
  'darksalmon': Chroma('E9967A'),
  'darkseagreen': Chroma('8FBC8F'),
  'darkslateblue': Chroma('483D8B'),
  'darkslategray': Chroma('2F4F4F'),
  'darkslategrey': Chroma('2F4F4F'),
  'darkturquoise': Chroma('00CED1'),
  'darkviolet': Chroma('9400D3'),
  'deeppink': Chroma('FF1493'),
  'deepskyblue': Chroma('00BFFF'),
  'dimgray': Chroma('696969'),
  'dimgrey': Chroma('696969'),
  'dodgerblue': Chroma('1E90FF'),
  'firebrick': Chroma('B22222'),
  'floralwhite': Chroma('FFFAF0'),
  'forestgreen': Chroma('228B22'),
  'fuchsia': Chroma('FF00FF'),
  'gainsboro': Chroma('DCDCDC'),
  'ghostwhite': Chroma('F8F8FF'),
  'gold': Chroma('FFD700'),
  'goldenrod': Chroma('DAA520'),
  'gray': Chroma('808080'),
  'green': Chroma('008000'),
  'greenyellow': Chroma('ADFF2F'),
  'grey': Chroma('808080'),
  'honeydew': Chroma('F0FFF0'),
  'hotpink': Chroma('FF69B4'),
  'indianred': Chroma('CD5C5C'),
  'indigo': Chroma('4B0082'),
  'ivory': Chroma('FFFFF0'),
  'khaki': Chroma('F0E68C'),
  'lavender': Chroma('E6E6FA'),
  'lavenderblush': Chroma('FFF0F5'),
  'lawngreen': Chroma('7CFC00'),
  'lemonchiffon': Chroma('FFFACD'),
  'lightblue': Chroma('ADD8E6'),
  'lightcoral': Chroma('F08080'),
  'lightcyan': Chroma('E0FFFF'),
  'lightgoldenrodyellow': Chroma('FAFAD2'),
  'lightgray': Chroma('D3D3D3'),
  'lightgreen': Chroma('90EE90'),
  'lightgrey': Chroma('D3D3D3'),
  'lightpink': Chroma('FFB6C1'),
  'lightsalmon': Chroma('FFA07A'),
  'lightseagreen': Chroma('20B2AA'),
  'lightskyblue': Chroma('87CEFA'),
  'lightslategray': Chroma('778899'),
  'lightslategrey': Chroma('778899'),
  'lightsteelblue': Chroma('B0C4DE'),
  'lightyellow': Chroma('FFFFE0'),
  'lime': Chroma('00FF00'),
  'limegreen': Chroma('32CD32'),
  'linen': Chroma('FAF0E6'),
  'magenta': Chroma('FF00FF'),
  'maroon': Chroma('800000'),
  'mediumaquamarine': Chroma('66CDAA'),
  'mediumblue': Chroma('0000CD'),
  'mediumorchid': Chroma('BA55D3'),
  'mediumpurple': Chroma('9370DB'),
  'mediumseagreen': Chroma('3CB371'),
  'mediumslateblue': Chroma('7B68EE'),
  'mediumspringgreen': Chroma('00FA9A'),
  'mediumturquoise': Chroma('48D1CC'),
  'mediumvioletred': Chroma('C71585'),
  'midnightblue': Chroma('191970'),
  'mintcream': Chroma('F5FFFA'),
  'mistyrose': Chroma('FFE4E1'),
  'moccasin': Chroma('FFE4B5'),
  'navajowhite': Chroma('FFDEAD'),
  'navy': Chroma('000080'),
  'oldlace': Chroma('FDF5E6'),
  'olive': Chroma('808000'),
  'olivedrab': Chroma('6B8E23'),
  'orange': Chroma('FFA500'),
  'orangered': Chroma('FF4500'),
  'orchid': Chroma('DA70D6'),
  'palegoldenrod': Chroma('EEE8AA'),
  'palegreen': Chroma('98FB98'),
  'paleturquoise': Chroma('AFEEEE'),
  'palevioletred': Chroma('DB7093'),
  'papayawhip': Chroma('FFEFD5'),
  'peachpuff': Chroma('FFDAB9'),
  'peru': Chroma('CD853F'),
  'pink': Chroma('FFC0CB'),
  'plum': Chroma('DDA0DD'),
  'powderblue': Chroma('B0E0E6'),
  'purple': Chroma('800080'),
  'rebeccapurple': Chroma('663399'),
  'red': Chroma('FF0000'),
  'rosybrown': Chroma('BC8F8F'),
  'royalblue': Chroma('4169E1'),
  'saddlebrown': Chroma('8B4513'),
  'salmon': Chroma('FA8072'),
  'sandybrown': Chroma('F4A460'),
  'seagreen': Chroma('2E8B57'),
  'seashell': Chroma('FFF5EE'),
  'sienna': Chroma('A0522D'),
  'silver': Chroma('C0C0C0'),
  'skyblue': Chroma('87CEEB'),
  'slateblue': Chroma('6A5ACD'),
  'slategray': Chroma('708090'),
  'slategrey': Chroma('708090'),
  'snow': Chroma('FFFAFA'),
  'springgreen': Chroma('00FF7F'),
  'steelblue': Chroma('4682B4'),
  'tan': Chroma('D2B48C'),
  'teal': Chroma('008080'),
  'thistle': Chroma('D8BFD8'),
  'tomato': Chroma('FF6347'),
  'turquoise': Chroma('40E0D0'),
  'violet': Chroma('EE82EE'),
  'wheat': Chroma('F5DEB3'),
  'white': Chroma('FFFFFF'),
  'whitesmoke': Chroma('F5F5F5'),
  'yellow': Chroma('FFFF00'),
  'yellowgreen': Chroma('9ACD32'),
};
